{:user {:plugins [[lein-pprint "1.1.2"]
                  [lein-cljsbuild "1.1.5"]
                  [lein-ancient "0.6.10" :exclusions [org.clojure/clojure]]
                  [lein-kibit "0.1.3"]
                  [com.jakemccrary/lein-test-refresh "0.19.0"]
                  [cider/cider-nrepl "0.15.1-SNAPSHOT"]
                  [refactor-nrepl "2.4.0-SNAPSHOT"]
                  [jonase/eastwood "0.2.3"]
                  [lein-license "0.1.6"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.13"]]}}
