{:user {:plugins [[lein-pprint "1.1.2"]
                  [lein-cljsbuild "1.1.5"]
                  [lein-ancient "0.6.10"]
                  [lein-midje "3.2.1"]
                  [lein-kibit "0.1.3"]
                  [lein-typed "0.3.5"]
                  [com.jakemccrary/lein-test-refresh "0.19.0"]
                  [cider/cider-nrepl "0.15.0-SNAPSHOT"]
                  [refactor-nrepl "2.3.0"]
                  [jonase/eastwood "0.2.3"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.12"]]}}
