{:user {:plugins [[lein-pprint "1.2.0"]
                  [lein-cljsbuild "1.1.7"]
                  [lein-ancient "0.6.15" :exclusions [org.clojure/clojure]]
                  [lein-kibit "0.1.6"]
                  [com.jakemccrary/lein-test-refresh "0.22.0"]
                  [cider/cider-nrepl "0.18.0-SNAPSHOT"]
                  [refactor-nrepl "2.4.0-SNAPSHOT"]
                  [jonase/eastwood "0.2.6"]
                  [lein-license "0.1.6"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.13"]]}}
